http:
  port: 8080
admin:
  port: 9876
  hostname: localhost
apiEndpoints:
  flaskmicro:
    host: '*'
    paths: '/flask/*'
  javamicro:
    host: '*'
    paths: '/sciencegateway/webapi/hello/*'
  dbmicroinsert:
    host: '*'
    paths: '/sciencegateway/webapi/register/*'
  dbmicroget:
    host: '*'
    paths: '/sciencegateway/webapi/register'
  uitarget:
    host: '*'
    paths: '/*'
    
serviceEndpoints:
  inputendpoint:
    url: 'http://localhost:5000'
  micro2:
    url: 'http://localhost:9090'
  ui:
    url: 'http://127.0.0.1:53238'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  - name: default
    apiEndpoints:
      - flaskmicro
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: inputendpoint 
              changeOrigin: true
  - name: micro2endpoint
    apiEndpoints:
      - javamicro
      - dbmicroinsert
      - dbmicroget
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: micro2 
              changeOrigin: true
  - name: uiendpoint
    apiEndpoints:
      - uitarget
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: ui 
              changeOrigin: true
